var testDate = new Date(); //IF NO TEST LEAVE DATE BLANK ELSE TYPE TEST DATE IN XX-XX-XX FORM
var sheetName = "Ventura"; //IF NO COMP LEAVE AS "TEST"
var matchNum; //LEAVE UNINITIALIZED IF COMP

localStorage.clear() //IF TESTING LEAVE UNCOMMENTED